package com.spacemax.entities;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Input;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.math.Rectangle;

public class Ship {
    private float x;
    private float y;
    private float speed = 400f; // pixels per second
    private float width = 80;
    private float height = 80;
    
    private float laserCooldown = 0.2f;
    private float timeSinceLastShot = 0;

    public Ship() {
        // Set initial ship position (bottom center)
        this.x = Gdx.graphics.getWidth() / 2f - width / 2f;
        this.y = 20; // 20 pixels from bottom
    }

    public void update(float delta) {
        timeSinceLastShot += delta;

        // Movement logic
        if (Gdx.input.isKeyPressed(Input.Keys.LEFT)) {
            x -= speed * delta;
        }
        if (Gdx.input.isKeyPressed(Input.Keys.RIGHT)) {
            x += speed * delta;
        }

        // Clamp to screen bounds
        if (x < 0) {
            x = 0;
        }
        if (x > Gdx.graphics.getWidth() - width) {
            x = Gdx.graphics.getWidth() - width;
        }
    }

    public Laser shoot() {
        if (Gdx.input.isKeyPressed(Input.Keys.SPACE) && timeSinceLastShot >= laserCooldown) {
            timeSinceLastShot = 0;
            return new Laser(x + width / 2f - 3f, y + height);
        }
        return null;
    }

    public void draw(SpriteBatch batch, Texture texture) {
        // Draw spaceship (additive blending to hide black background if generated by AI)
        batch.setBlendFunction(GL20.GL_SRC_ALPHA, GL20.GL_ONE);
        batch.draw(texture, x, y, width, height);
        batch.setBlendFunction(GL20.GL_SRC_ALPHA, GL20.GL_ONE_MINUS_SRC_ALPHA); // Reset to default
    }

    public Rectangle getBounds() {
        // slightly smaller hitbox for fairness
        return new Rectangle(x + 15, y + 15, width - 30, height - 30);
    }
}
